services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # Services
    Umbrella\AdminBundle\Services\AdminConfigService:
        public: true

    # Sidebar
    Umbrella\AdminBundle\Menu\SidebarMenu:
        arguments: [null]
        public: true
        tags:
          - { name: umbrella.menu.factory, method: createMenu, alias: admin_sidebar }

    Umbrella\AdminBundle\Menu\SideBarMenuRenderer:
        public: true
        tags:
          - { name: umbrella.menu_renderer, alias: admin_sidebar }

    #Twig
    Umbrella\AdminBundle\Twig\AdminTwigExtension: