services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # Controllers
    Umbrella\AdminBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: ['controller.service_arguments']

    # Table
    Umbrella\AdminBundle\DataTable\UserGroupTableType:
    Umbrella\AdminBundle\DataTable\UserTableType:
    Umbrella\AdminBundle\DataTable\TaskTableType:

    # Form
    Umbrella\AdminBundle\Form\ProfileType:
    Umbrella\AdminBundle\Form\UserGroupType:
    Umbrella\AdminBundle\Form\UserPasswordConfirmType:
    Umbrella\AdminBundle\Form\UserType:

    # Security
    Umbrella\AdminBundle\Security\AuthenticationEntryPoint:
    Umbrella\AdminBundle\Security\UserProvider:
    Umbrella\AdminBundle\Security\UserChecker:

    # Services
    Umbrella\AdminBundle\Services\UserGroupManager:
        public: true
    Umbrella\AdminBundle\Services\UserManager:
        public: true
    Umbrella\AdminBundle\Services\UserMailer:
        public: true


    # Sidebar
    Umbrella\AdminBundle\Menu\SidebarMenu:
        arguments: [null]
        public: true
        tags:
          - { name: umbrella.menu.factory, method: createMenu, alias: admin_sidebar }

    Umbrella\AdminBundle\Menu\SideBarMenuRenderer:
        public: true
        tags:
          - { name: umbrella.menu_renderer, alias: admin_sidebar }

    # FileWriter
    Umbrella\AdminBundle\FileWriter\Handler\FileWriterHandlerFactory:
    Umbrella\AdminBundle\FileWriter\Handler\TaskFileWriterHandler:
    Umbrella\AdminBundle\FileWriter\FileWriterManager:
        public: true
        bind:
            $outputDirPath: "%umbrella_admin.filewriter.output_path%"

    #Twig
    Umbrella\AdminBundle\Extension\AdminTwigExtension: