services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # Controllers
    Umbrella\AdminBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: ['controller.service_arguments']

    Umbrella\AdminBundle\Controller\SecurityController:
        bind:
            $retryTtl: "%umbrella_admin.user.security.password_request_ttl%"

    # Table
    Umbrella\AdminBundle\DataTable\UserGroupTableType:
    Umbrella\AdminBundle\DataTable\UserTableType:
    Umbrella\AdminBundle\DataTable\JobTableType:

    # Form
    Umbrella\AdminBundle\Form\ProfileType:
    Umbrella\AdminBundle\Form\UserGroupType:
    Umbrella\AdminBundle\Form\UserPasswordConfirmType:
    Umbrella\AdminBundle\Form\UserType:

    # Security
    Umbrella\AdminBundle\Security\AuthenticationEntryPoint:
    Umbrella\AdminBundle\Security\UserProvider:
    Umbrella\AdminBundle\Security\UserChecker:

    # Services
    Umbrella\AdminBundle\Services\UserGroupManager:
        public: true
    Umbrella\AdminBundle\Services\UserManager:
        public: true
    Umbrella\AdminBundle\Services\UserMailer:
        public: true

    # Sidebar
    Umbrella\AdminBundle\Menu\SidebarMenu:
        public: true
        bind:
            $ymlPath: "%umbrella_admin.menu.file%"
        tags:
          - { name: umbrella.menu.factory, method: createMenu, alias: admin_sidebar }
          - { name: umbrella.menu.renderer, method: renderMenu, alias: admin_sidebar }
          - { name: umbrella.breadcrumb.renderer, method: renderBreadcrumb, alias: admin_sidebar }

    # FileWriter
    Umbrella\AdminBundle\FileWriter\FileWriter:
        public: true
        bind:
            $outputDirPath: "%umbrella_admin.filewriter.output_path%"
            $maxFileWrite: "%umbrella_admin.filewriter.max_task%"
    #Twig
    Umbrella\AdminBundle\Extension\AdminTwigExtension: